### ISSUE TITLE
Use password hashing here

### ISSUE THREAD

**Issue by mmallett** [mallett002/Train-Like-Me#10]
https://github.com/mallett002/Train-Like-Me/blob/d28d375591f839b9ebbc0db1dca1908d97699b62/src/app-root/App.js#L25

You are sending plaintext passwords over the network to firebase and storing plaintext passwords in the database. Don't do that.

Proper way to store user's passwords is to hash them into a random string. When you log in, you compare the hash of the input password with the hash you have stored in database.

"Salting" the hash generates extra randomness so malicious users can't precompute thousands of common password hashes.

Example:
https://ciphertrick.com/salt-hash-passwords-using-nodejs-crypto/

More about this..
https://auth0.com/blog/adding-salt-to-hashing-a-better-way-to-store-passwords/

**Comment by yoans** [comment]
https://firebaseopensource.com/projects/firebase/scrypt/
firebase handles secure storing of the hashed passwords.
Https secures the information on the network.
Not perfectly secure, but well within reasonable standards for a webapp that doesn't handle sensitive information.

**Comment by joshmccall221** [comment]
@mmallett, like @yoans mentioned, firebase handles the password, https call, and returns an idToken. We never see/store the password.

Let us know if you see a gap ...

**Comment by mmallett** [comment]
lgtm
